### ISSUE TITLE
read from a range of cells

### ISSUE THREAD

**Issue by simkimsia** [pyexcel/pyexcel#117]
Hi there, 

Was wondering if there's a way to specify in pyexcel reading from a range of cells 

e.g. A3 to G7
e.g. B2 to B10 
e.g. C4 to H4

instead of reading an entire sheet?

it need not be a single function that does this. I am okay if need to use a few other functions.

Something like https://stackoverflow.com/a/33938163/80353
or http://openpyxl.readthedocs.io/en/stable/tutorial.html#accessing-many-cells

**Comment by chfw** [comment]
It is possible with [start_row, row_limit, start_column and column_limit](http://pyexcel.readthedocs.io/en/latest/bigdata.html) parameters. However, those parameters are not based on excel naming conventions.

**Comment by chfw** [comment]
with pyexcel-odsr and pyexcel-xlsxr as file readers, those parameters works in a more memory efficient way, because they do not read all into memory(partial reading) whereas pyexcel-ods, pyexcel-ods3 and pyexcel-xlsx would do a full reading.

**Comment by chfw** [comment]
In your python path or python virtual environment, if you have more than one reader candidates for a file type, you need to tell pyexcel to choose one using `library` parameter. Otherwise, you can simply do a get_sheet. So this is down to your requirements.txt and your project. 

For example: pyexcel-xls, pyexcel-xlsx and pyexcel-xlsxr, all have a reader for xlsx format. If you have all of them installed in your environment, you need to tell get_sheet with `library="pyexcel-xlsxr"`. Alternatively, if you do not need the extra readers for your project, you can uninstall others but keep pyexcel-xlsxr. In this way, you can simply call get_sheet without the `library` parameter
